### PR TITLE
Enhance logging for expected DSP module-unavailable errors

### LINKED ISSUE #297: Scary messages on normal startup
### FastRPC version

v1.0.2

### DSP firmware version

QC_IMAGE_VERSION_STRING=DSP.AT.1.0.1-00170-LEMANS-1

### SoC and device name

Monaco EVK (RB4) QCS8275 (QCS8300)

### Kernel version

6.19.0-g1cfc3259c7dc

### What happened?

After installing fastrpc and related packages (hexagon-dsp-binaries), a normal startup shows a lot of errors in the journal

I actually think these errors are benign, but:
- they are scary for developers
- they participate in hiding real issues that might pop up

Image

### Steps to reproduce

Install fastrpc packages and firmware dependencies, reboot, check journalctl

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by quic-vkatoch**
Handle AEE_ENOSUCHMOD as an expected module-availability conditions by logging them at FARF(ALWAYS) with a "Warning:" prefix instead of FARF(ERROR) in fastrpc_apps_user.c and listener_android.c. This reduces unnecessary error-noise while preserving ERROR logs for unexpected failures.

Fixes: #297

### CODE REVIEW

File: src/fastrpc_apps_user.c [hunk 1]
```diff
@@ -1488,11 +1488,19 @@ int remote_handle64_invoke(remote_handle64 local, uint32_t sc,
     }
     if (0 == check_rpc_error(nErr)) {
       if (get_logger_state(domain)) {
-        FARF(ERROR,
-             "Error 0x%x: %s failed for module %s, handle 0x%" PRIx64
-             ", method %d on domain %d (sc 0x%x) (errno %s)\n",
-             nErr, __func__, h->name, local, REMOTE_SCALARS_METHOD(sc), domain, sc,
-             strerror(errno));
+        if (nErr == (int)(DSP_AEE_EOFFSET + AEE_ENOSUCHMOD)) {
+          FARF(ALWAYS,
```
Comment (ekanshibu) [inline src/fastrpc_apps_user.c:1492]: Rephrase the log suggesting the module is not supported by DSP.

File: src/listener_android.c [hunk 2]
```diff
@@ -349,7 +349,7 @@ static void *listener_start_thread(void *arg) {
     nErr = __QAIC_HEADER(adsp_listener1_init2)(adsp_listener1_handle);
     if ((nErr == DSP_AEE_EOFFSET + AEE_ERPC) ||
         nErr == DSP_AEE_EOFFSET + AEE_ENOSUCHMOD) {
-      FARF(ERROR, "Error 0x%x: %s domains support not available in listener",
+      FARF(ALWAYS, "Warning 0x%x: %s domains support not available in listener",
```
Comment (ekanshibu) [inline src/listener_android.c]: same comment as above, is error code logging really needed here?

Comment (quic-vkatoch) [reply src/listener_android.c]: Removed the error code to avoid confusion

**Review by ekanshibu — APPROVED** [review]

**Review by Chennak-quic — APPROVED** [review]
